### ISSUE TITLE
running /shortcut alone causes thelounge to restart

### ISSUE THREAD

**Issue by igalic** [MiniDigger/thelounge-plugin-shortcuts#17]
and i think that's kinda poor error handling :stuck_out_tongue_closed_eyes: 

```
2019-12-30 21:31:06 [INFO] User meena loaded
2019-12-30 21:31:06 [INFO] [Shortcuts] Loaded 0 shortcuts from /srv/thelounge/packages/shortcuts.json

/srv/thelounge/packages/node_modules/thelounge-plugin-shortcuts/index.js:112
             client.sendMessage(red + "Usage: /shortcut <add|list|remove>", target.chan);
                    ^
 
TypeError: client.sendMessage is not a function
     at Object.input (/srv/thelounge/packages/node_modules/thelounge-plugin-shortcuts/index.js:112:20)
     at Client.inputLine (/usr/local/lib/node_modules/thelounge/src/client.js:376:11)
     at data.text.split.forEach (/usr/local/lib/node_modules/thelounge/src/client.js:322:10)
     at Array.forEach (<anonymous>)
     at Client.input (/usr/local/lib/node_modules/thelounge/src/client.js:320:24)
     at Socket.socket.on (/usr/local/lib/node_modules/thelounge/src/server.js:361:11)
     at Socket.emit (events.js:198:13)
     at /usr/local/lib/node_modules/thelounge/node_modules/socket.io/lib/socket.js:528:12
     at process._tickCallback (internal/process/next_tick.js:61:11)
2019-12-30 21:32:12 [INFO] The Lounge v3.3.0 (Node.js 10.17.0 on freebsd x64)
2019-12-30 21:32:12 [INFO] Configuration file: /srv/thelounge/config.js
2019-12-30 21:32:12 [INFO] Available at http://:::9000/ in private mode
2019-12-30 21:32:12 [INFO] Package thelounge-plugin-shortcuts loaded
2019-12-30 21:32:12 [INFO] There are packages using the experimental plugin API. Be aware that this API is not yet stable and may change in future The Lounge releases.
2019-12-30 21:32:12 [INFO] User meena loaded
2019-12-30 21:32:13 [INFO] [Shortcuts] Loaded 0 shortcuts from /srv/thelounge/packages/shortcuts.json
```

**Comment by MiniDigger** [comment]
for further reference, this plugin requires thelounge 4.0+
